// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWKT
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

extension Clients {
  protocol AccessPoliciesStub: Sendable {
    func createAccessPolicy(
      request: CreateAccessPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getAccessPolicy(
      request: GetAccessPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV3.AccessPolicy

    func updateAccessPolicy(
      request: UpdateAccessPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteAccessPolicy(
      request: DeleteAccessPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listAccessPolicies(
      request: ListAccessPoliciesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV3.ListAccessPoliciesResponse

    func searchAccessPolicyBindings(
      request: SearchAccessPolicyBindingsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV3.SearchAccessPolicyBindingsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation
  }
}
