// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// An IAM access policy resource.
public struct AccessPolicy: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Identifier. The resource name of the access policy.
  ///
  /// The following formats are supported:
  ///
  /// * `projects/{project_id}/locations/{location}/accessPolicies/{policy_id}`
  /// * `projects/{project_number}/locations/{location}/accessPolicies/{policy_id}`
  /// * `folders/{folder_id}/locations/{location}/accessPolicies/{policy_id}`
  /// * `organizations/{organization_id}/locations/{location}/accessPolicies/{policy_id}`
  public var name: Swift.String = Swift.String()

  /// Output only. The globally unique ID of the access policy.
  public var uid: Swift.String = Swift.String()

  /// Optional. The etag for the access policy.
  /// If this is provided on update, it must match the server's etag.
  public var etag: Swift.String = Swift.String()

  /// Optional. The description of the access policy. Must be less than
  /// or equal to 63 characters.
  public var displayName: Swift.String = Swift.String()

  /// Optional. User defined annotations. See
  /// https://google.aip.dev/148#annotations for more details such as format and
  /// size limitations
  public var annotations: [Swift.String: Swift.String] = [:]

  /// Output only. The time when the access policy was created.
  public var createTime: GoogleWKT.Timestamp? = nil

  /// Output only. The time when the access policy was most recently
  /// updated.
  public var updateTime: GoogleWKT.Timestamp? = nil

  /// Optional. The details for the access policy.
  public var details: AccessPolicyDetails? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `AccessPolicy`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AccessPolicy().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let uid = CodingKeys(stringValue: "uid")
    static let etag = CodingKeys(stringValue: "etag")
    static let displayName = CodingKeys(stringValue: "displayName")
    static let annotations = CodingKeys(stringValue: "annotations")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let details = CodingKeys(stringValue: "details")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "uid",
      "etag",
      "displayName",
      "annotations",
      "createTime",
      "updateTime",
      "details",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .uid) {
      self.uid = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .etag) {
      self.etag = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .displayName) {
      self.displayName = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .annotations)
    {
      self.annotations = value
    }
    self.createTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .updateTime)
    self.details = try container.decodeIfPresent(AccessPolicyDetails.self, forKey: .details)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.uid, forKey: .uid)
    try container.encode(self.etag, forKey: .etag)
    try container.encode(self.displayName, forKey: .displayName)
    try container.encode(self.annotations, forKey: .annotations)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encodeIfPresent(self.details, forKey: .details)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.iam.v3.AccessPolicy"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
