// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleLongRunning
@_spi(GoogleCloudInternal) public import GoogleGax

/// Manages Identity and Access Management (IAM) access policies.
///
/// @Snippet(path: "AccessPoliciesQuickstart")
public final class AccessPoliciesClient: Clients.AccessPoliciesProtocol, Sendable {
  let inner: any Clients.AccessPoliciesStub
  let pollingErrorPolicy: GoogleGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleGax.BackoffPolicy

  /// Creates a new `AccessPoliciesClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.AccessPoliciesStub = try Clients.AccessPoliciesTransport(options)
    inner = Clients.AccessPoliciesRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.AccessPoliciesLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Creates an access policy, and returns a long running operation.
  ///
  /// @Snippet(path: "AccessPolicies_CreateAccessPolicy")
  public func createAccessPolicy(
    request: CreateAccessPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createAccessPolicy(request: request, options: options)
  }

  /// Creates an access policy, and returns a long running operation.
  ///
  /// @Snippet(path: "AccessPolicies_CreateAccessPolicy")
  public func createAccessPolicyPollingUntilDone(
    request: CreateAccessPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<AccessPolicy> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<AccessPolicy>.State in
      return try op._extractStatus(AccessPolicy.self)
    }
    let rawOp = try await self.createAccessPolicy(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<AccessPolicy>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Gets an access policy.
  ///
  /// @Snippet(path: "AccessPolicies_GetAccessPolicy")
  public func getAccessPolicy(
    request: GetAccessPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV3.AccessPolicy {
    try await self.inner.getAccessPolicy(request: request, options: options)
  }

  /// Updates an access policy.
  ///
  /// @Snippet(path: "AccessPolicies_UpdateAccessPolicy")
  public func updateAccessPolicy(
    request: UpdateAccessPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateAccessPolicy(request: request, options: options)
  }

  /// Updates an access policy.
  ///
  /// @Snippet(path: "AccessPolicies_UpdateAccessPolicy")
  public func updateAccessPolicyPollingUntilDone(
    request: UpdateAccessPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<AccessPolicy> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<AccessPolicy>.State in
      return try op._extractStatus(AccessPolicy.self)
    }
    let rawOp = try await self.updateAccessPolicy(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<AccessPolicy>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes an access policy.
  ///
  /// @Snippet(path: "AccessPolicies_DeleteAccessPolicy")
  public func deleteAccessPolicy(
    request: DeleteAccessPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteAccessPolicy(request: request, options: options)
  }

  /// Deletes an access policy.
  ///
  /// @Snippet(path: "AccessPolicies_DeleteAccessPolicy")
  public func deleteAccessPolicyPollingUntilDone(
    request: DeleteAccessPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteAccessPolicy(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists access policies.
  ///
  /// @Snippet(path: "AccessPolicies_ListAccessPolicies")
  public func listAccessPolicies(
    request: ListAccessPoliciesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV3.ListAccessPoliciesResponse {
    try await self.inner.listAccessPolicies(request: request, options: options)
  }

  /// Returns all policy bindings that bind a specific policy if a user has
  /// searchPolicyBindings permission on that policy.
  ///
  /// @Snippet(path: "AccessPolicies_SearchAccessPolicyBindings")
  public func searchAccessPolicyBindings(
    request: SearchAccessPolicyBindingsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV3.SearchAccessPolicyBindingsResponse {
    try await self.inner.searchAccessPolicyBindings(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "AccessPolicies_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `AccessPoliciesClient`.
  ///
  /// To mock `AccessPoliciesClient` change your functions to receive
  /// `some AccessPoliciesProtocol` or `any AccessPoliciesProtocol`
  /// and pass a mock implementation in your tests.
  public protocol AccessPoliciesProtocol: Sendable {
    /// See `AccessPoliciesClient.createAccessPolicy`.
    func createAccessPolicy(
      request: CreateAccessPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AccessPoliciesClient.createAccessPolicy`.
    func createAccessPolicyPollingUntilDone(
      request: CreateAccessPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<AccessPolicy>

    /// See `AccessPoliciesClient.getAccessPolicy`.
    func getAccessPolicy(
      request: GetAccessPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV3.AccessPolicy

    /// See `AccessPoliciesClient.updateAccessPolicy`.
    func updateAccessPolicy(
      request: UpdateAccessPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AccessPoliciesClient.updateAccessPolicy`.
    func updateAccessPolicyPollingUntilDone(
      request: UpdateAccessPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<AccessPolicy>

    /// See `AccessPoliciesClient.deleteAccessPolicy`.
    func deleteAccessPolicy(
      request: DeleteAccessPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AccessPoliciesClient.deleteAccessPolicy`.
    func deleteAccessPolicyPollingUntilDone(
      request: DeleteAccessPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `AccessPoliciesClient.listAccessPolicies`.
    func listAccessPolicies(
      request: ListAccessPoliciesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV3.ListAccessPoliciesResponse

    /// See `AccessPoliciesClient.searchAccessPolicyBindings`.
    func searchAccessPolicyBindings(
      request: SearchAccessPolicyBindingsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV3.SearchAccessPolicyBindingsResponse
  }
}

// Default implementations
extension Clients.AccessPoliciesProtocol {
  public func createAccessPolicy(request: CreateAccessPolicyRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createAccessPolicy(request: request, options: .init())
  }

  public func createAccessPolicy(
    request: CreateAccessPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createAccessPolicyPollingUntilDone(request: CreateAccessPolicyRequest) async throws
    -> any GoogleGax.PollableOperation<AccessPolicy>
  {
    try await self.createAccessPolicyPollingUntilDone(request: request, options: .init())
  }

  public func createAccessPolicyPollingUntilDone(
    request: CreateAccessPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<AccessPolicy> {
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<AccessPolicy>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createAccessPolicyPollingUntilDone(
    parent: Swift.String,
    accessPolicy: AccessPolicy?,
    accessPolicyId: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<AccessPolicy> {
    let request = CreateAccessPolicyRequest().with {
      $0.parent = parent
      $0.accessPolicy = accessPolicy
      $0.accessPolicyId = accessPolicyId
    }
    return try await self.createAccessPolicyPollingUntilDone(request: request)
  }

  public func getAccessPolicy(request: GetAccessPolicyRequest) async throws
    -> GoogleIAMV3.AccessPolicy
  {
    try await self.getAccessPolicy(request: request, options: .init())
  }

  public func getAccessPolicy(
    request: GetAccessPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV3.AccessPolicy {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getAccessPolicy(
    name: Swift.String,
  ) async throws -> GoogleIAMV3.AccessPolicy {
    let request = GetAccessPolicyRequest().with {
      $0.name = name
    }
    return try await self.getAccessPolicy(request: request)
  }

  public func updateAccessPolicy(request: UpdateAccessPolicyRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateAccessPolicy(request: request, options: .init())
  }

  public func updateAccessPolicy(
    request: UpdateAccessPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updateAccessPolicyPollingUntilDone(request: UpdateAccessPolicyRequest) async throws
    -> any GoogleGax.PollableOperation<AccessPolicy>
  {
    try await self.updateAccessPolicyPollingUntilDone(request: request, options: .init())
  }

  public func updateAccessPolicyPollingUntilDone(
    request: UpdateAccessPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<AccessPolicy> {
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<AccessPolicy>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteAccessPolicy(request: DeleteAccessPolicyRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteAccessPolicy(request: request, options: .init())
  }

  public func deleteAccessPolicy(
    request: DeleteAccessPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deleteAccessPolicyPollingUntilDone(request: DeleteAccessPolicyRequest) async throws
    -> any GoogleGax.PollableOperation<Swift.Void>
  {
    try await self.deleteAccessPolicyPollingUntilDone(request: request, options: .init())
  }

  public func deleteAccessPolicyPollingUntilDone(
    request: DeleteAccessPolicyRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteAccessPolicyPollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let request = DeleteAccessPolicyRequest().with {
      $0.name = name
    }
    return try await self.deleteAccessPolicyPollingUntilDone(request: request)
  }

  public func listAccessPolicies(request: ListAccessPoliciesRequest) async throws
    -> GoogleIAMV3.ListAccessPoliciesResponse
  {
    try await self.listAccessPolicies(request: request, options: .init())
  }

  public func listAccessPolicies(
    request: ListAccessPoliciesRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV3.ListAccessPoliciesResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listAccessPoliciesByItems(
    request: ListAccessPoliciesRequest
  ) -> some AsyncSequence<AccessPolicy, Swift.Error> & Sendable {
    self.listAccessPoliciesByItems(request: request, options: .init())
  }

  /// Lists access policies.
  ///
  /// @Snippet(path: "AccessPolicies_ListAccessPolicies")
  public func listAccessPoliciesByItems(
    request: ListAccessPoliciesRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<AccessPolicy, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleIAMV3.ListAccessPoliciesResponse in
      var request = request
      request.pageToken = token
      return try await self.listAccessPolicies(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listAccessPoliciesByItems(
    parent: Swift.String,
  ) -> some AsyncSequence<AccessPolicy, Swift.Error> & Sendable {
    let request = ListAccessPoliciesRequest().with {
      $0.parent = parent
    }
    return self.listAccessPoliciesByItems(request: request)
  }

  public func searchAccessPolicyBindings(request: SearchAccessPolicyBindingsRequest) async throws
    -> GoogleIAMV3.SearchAccessPolicyBindingsResponse
  {
    try await self.searchAccessPolicyBindings(request: request, options: .init())
  }

  public func searchAccessPolicyBindings(
    request: SearchAccessPolicyBindingsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV3.SearchAccessPolicyBindingsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func searchAccessPolicyBindingsByItems(
    request: SearchAccessPolicyBindingsRequest
  ) -> some AsyncSequence<PolicyBinding, Swift.Error> & Sendable {
    self.searchAccessPolicyBindingsByItems(request: request, options: .init())
  }

  /// Returns all policy bindings that bind a specific policy if a user has
  /// searchPolicyBindings permission on that policy.
  ///
  /// @Snippet(path: "AccessPolicies_SearchAccessPolicyBindings")
  public func searchAccessPolicyBindingsByItems(
    request: SearchAccessPolicyBindingsRequest, options: GoogleGax.RequestOptions
  ) -> some AsyncSequence<PolicyBinding, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleIAMV3.SearchAccessPolicyBindingsResponse
      in
      var request = request
      request.pageToken = token
      return try await self.searchAccessPolicyBindings(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func searchAccessPolicyBindingsByItems(
    name: Swift.String,
  ) -> some AsyncSequence<PolicyBinding, Swift.Error> & Sendable {
    let request = SearchAccessPolicyBindingsRequest().with {
      $0.name = name
    }
    return self.searchAccessPolicyBindingsByItems(request: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }
}
