// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

/// Manages Identity and Access Management (IAM) access policies.
///
/// @Snippet(path: "AccessPoliciesQuickstart")
public final class AccessPoliciesClient: Clients.AccessPoliciesProtocol, Sendable {
  let inner: any Clients.AccessPoliciesStub
  let pollingErrorPolicy: GoogleCloudGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleCloudGax.BackoffPolicy

  /// Creates a new `AccessPoliciesClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.AccessPoliciesStub = try Clients.AccessPoliciesTransport(options)
    inner = Clients.AccessPoliciesRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.AccessPoliciesLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Creates an access policy, and returns a long running operation.
  ///
  /// @Snippet(path: "AccessPolicies_CreateAccessPolicy")
  public func createAccessPolicy(
    request: CreateAccessPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createAccessPolicy(request: request, options: options)
  }

  /// Creates an access policy, and returns a long running operation.
  ///
  /// @Snippet(path: "AccessPolicies_CreateAccessPolicy")
  public func createAccessPolicy(
    withPolling: CreateAccessPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<AccessPolicy> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<AccessPolicy>.State in
      return try op._extractStatus(AccessPolicy.self)
    }
    let rawOp = try await self.createAccessPolicy(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<AccessPolicy>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Gets an access policy.
  ///
  /// @Snippet(path: "AccessPolicies_GetAccessPolicy")
  public func getAccessPolicy(
    request: GetAccessPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIAMV3.AccessPolicy {
    try await self.inner.getAccessPolicy(request: request, options: options)
  }

  /// Updates an access policy.
  ///
  /// @Snippet(path: "AccessPolicies_UpdateAccessPolicy")
  public func updateAccessPolicy(
    request: UpdateAccessPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateAccessPolicy(request: request, options: options)
  }

  /// Updates an access policy.
  ///
  /// @Snippet(path: "AccessPolicies_UpdateAccessPolicy")
  public func updateAccessPolicy(
    withPolling: UpdateAccessPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<AccessPolicy> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<AccessPolicy>.State in
      return try op._extractStatus(AccessPolicy.self)
    }
    let rawOp = try await self.updateAccessPolicy(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<AccessPolicy>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes an access policy.
  ///
  /// @Snippet(path: "AccessPolicies_DeleteAccessPolicy")
  public func deleteAccessPolicy(
    request: DeleteAccessPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteAccessPolicy(request: request, options: options)
  }

  /// Deletes an access policy.
  ///
  /// @Snippet(path: "AccessPolicies_DeleteAccessPolicy")
  public func deleteAccessPolicy(
    withPolling: DeleteAccessPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteAccessPolicy(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists access policies.
  ///
  /// @Snippet(path: "AccessPolicies_ListAccessPolicies")
  public func listAccessPolicies(
    request: ListAccessPoliciesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIAMV3.ListAccessPoliciesResponse {
    try await self.inner.listAccessPolicies(request: request, options: options)
  }

  /// Lists access policies.
  ///
  /// @Snippet(path: "AccessPolicies_ListAccessPolicies")
  public func listAccessPolicies(
    byItem: ListAccessPoliciesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<AccessPolicy, Swift.Error> {
    let listRpc = { (token: Swift.String) async throws -> GoogleIAMV3.ListAccessPoliciesResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listAccessPolicies(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Returns all policy bindings that bind a specific policy if a user has
  /// searchPolicyBindings permission on that policy.
  ///
  /// @Snippet(path: "AccessPolicies_SearchAccessPolicyBindings")
  public func searchAccessPolicyBindings(
    request: SearchAccessPolicyBindingsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIAMV3.SearchAccessPolicyBindingsResponse {
    try await self.inner.searchAccessPolicyBindings(request: request, options: options)
  }

  /// Returns all policy bindings that bind a specific policy if a user has
  /// searchPolicyBindings permission on that policy.
  ///
  /// @Snippet(path: "AccessPolicies_SearchAccessPolicyBindings")
  public func searchAccessPolicyBindings(
    byItem: SearchAccessPolicyBindingsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<PolicyBinding, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleIAMV3.SearchAccessPolicyBindingsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.searchAccessPolicyBindings(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "AccessPolicies_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `AccessPoliciesClient`.
  ///
  /// To mock `AccessPoliciesClient` change your functions to receive
  /// `some AccessPoliciesProtocol` or `any AccessPoliciesProtocol`
  /// and pass a mock implementation in your tests.
  public protocol AccessPoliciesProtocol {
    /// See `AccessPoliciesClient.createAccessPolicy`.
    func createAccessPolicy(request: CreateAccessPolicyRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `AccessPoliciesClient.createAccessPolicy`.
    func createAccessPolicy(withPolling: CreateAccessPolicyRequest) async throws
      -> any GoogleCloudGax.PollableOperation<AccessPolicy>

    /// See `AccessPoliciesClient.createAccessPolicy`.
    func createAccessPolicy(
      parent: Swift.String,
      accessPolicy: AccessPolicy?,
      accessPolicyId: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<AccessPolicy>

    /// See `AccessPoliciesClient.getAccessPolicy`.
    func getAccessPolicy(request: GetAccessPolicyRequest) async throws -> GoogleIAMV3.AccessPolicy

    /// See `AccessPoliciesClient.getAccessPolicy`.
    func getAccessPolicy(
      name: Swift.String,
    ) async throws -> GoogleIAMV3.AccessPolicy

    /// See `AccessPoliciesClient.updateAccessPolicy`.
    func updateAccessPolicy(request: UpdateAccessPolicyRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `AccessPoliciesClient.updateAccessPolicy`.
    func updateAccessPolicy(withPolling: UpdateAccessPolicyRequest) async throws
      -> any GoogleCloudGax.PollableOperation<AccessPolicy>

    /// See `AccessPoliciesClient.deleteAccessPolicy`.
    func deleteAccessPolicy(request: DeleteAccessPolicyRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `AccessPoliciesClient.deleteAccessPolicy`.
    func deleteAccessPolicy(withPolling: DeleteAccessPolicyRequest) async throws
      -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `AccessPoliciesClient.deleteAccessPolicy`.
    func deleteAccessPolicy(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `AccessPoliciesClient.listAccessPolicies`.
    func listAccessPolicies(request: ListAccessPoliciesRequest) async throws
      -> GoogleIAMV3.ListAccessPoliciesResponse

    /// See `AccessPoliciesClient.listAccessPolicies`.
    func listAccessPolicies(
      byItem: ListAccessPoliciesRequest
    ) throws -> any AsyncSequence<AccessPolicy, Swift.Error>

    /// See `AccessPoliciesClient.listAccessPolicies`.
    func listAccessPolicies(
      parent: Swift.String,
    ) throws -> any AsyncSequence<AccessPolicy, Swift.Error>

    /// See `AccessPoliciesClient.searchAccessPolicyBindings`.
    func searchAccessPolicyBindings(request: SearchAccessPolicyBindingsRequest) async throws
      -> GoogleIAMV3.SearchAccessPolicyBindingsResponse

    /// See `AccessPoliciesClient.searchAccessPolicyBindings`.
    func searchAccessPolicyBindings(
      byItem: SearchAccessPolicyBindingsRequest
    ) throws -> any AsyncSequence<PolicyBinding, Swift.Error>

    /// See `AccessPoliciesClient.searchAccessPolicyBindings`.
    func searchAccessPolicyBindings(
      name: Swift.String,
    ) throws -> any AsyncSequence<PolicyBinding, Swift.Error>

    /// See `AccessPoliciesClient.createAccessPolicy`.
    func createAccessPolicy(
      request: CreateAccessPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AccessPoliciesClient.createAccessPolicy`.
    func createAccessPolicy(
      withPolling: CreateAccessPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<AccessPolicy>

    /// See `AccessPoliciesClient.getAccessPolicy`.
    func getAccessPolicy(
      request: GetAccessPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV3.AccessPolicy

    /// See `AccessPoliciesClient.updateAccessPolicy`.
    func updateAccessPolicy(
      request: UpdateAccessPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AccessPoliciesClient.updateAccessPolicy`.
    func updateAccessPolicy(
      withPolling: UpdateAccessPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<AccessPolicy>

    /// See `AccessPoliciesClient.deleteAccessPolicy`.
    func deleteAccessPolicy(
      request: DeleteAccessPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `AccessPoliciesClient.deleteAccessPolicy`.
    func deleteAccessPolicy(
      withPolling: DeleteAccessPolicyRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `AccessPoliciesClient.listAccessPolicies`.
    func listAccessPolicies(
      request: ListAccessPoliciesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV3.ListAccessPoliciesResponse

    /// See `AccessPoliciesClient.listAccessPolicies`.
    func listAccessPolicies(
      byItem: ListAccessPoliciesRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<AccessPolicy, Swift.Error>

    /// See `AccessPoliciesClient.searchAccessPolicyBindings`.
    func searchAccessPolicyBindings(
      request: SearchAccessPolicyBindingsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV3.SearchAccessPolicyBindingsResponse

    /// See `AccessPoliciesClient.searchAccessPolicyBindings`.
    func searchAccessPolicyBindings(
      byItem: SearchAccessPolicyBindingsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<PolicyBinding, Swift.Error>
  }
}

// Default implementations
extension Clients.AccessPoliciesProtocol {
  public func createAccessPolicy(request: CreateAccessPolicyRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createAccessPolicy(request: request, options: .init())
  }

  public func createAccessPolicy(
    request: CreateAccessPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createAccessPolicy(withPolling: CreateAccessPolicyRequest) async throws
    -> any GoogleCloudGax.PollableOperation<AccessPolicy>
  {
    try await self.createAccessPolicy(withPolling: withPolling, options: .init())
  }

  public func createAccessPolicy(
    withPolling: CreateAccessPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<AccessPolicy> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<AccessPolicy>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createAccessPolicy(
    parent: Swift.String,
    accessPolicy: AccessPolicy?,
    accessPolicyId: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<AccessPolicy> {
    let request = CreateAccessPolicyRequest().with {
      $0.parent = parent
      $0.accessPolicy = accessPolicy
      $0.accessPolicyId = accessPolicyId
    }
    return try await self.createAccessPolicy(withPolling: request)
  }

  public func getAccessPolicy(request: GetAccessPolicyRequest) async throws
    -> GoogleIAMV3.AccessPolicy
  {
    try await self.getAccessPolicy(request: request, options: .init())
  }

  public func getAccessPolicy(
    request: GetAccessPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIAMV3.AccessPolicy {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getAccessPolicy(
    name: Swift.String,
  ) async throws -> GoogleIAMV3.AccessPolicy {
    let request = GetAccessPolicyRequest().with {
      $0.name = name
    }
    return try await self.getAccessPolicy(request: request)
  }

  public func updateAccessPolicy(request: UpdateAccessPolicyRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateAccessPolicy(request: request, options: .init())
  }

  public func updateAccessPolicy(
    request: UpdateAccessPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateAccessPolicy(withPolling: UpdateAccessPolicyRequest) async throws
    -> any GoogleCloudGax.PollableOperation<AccessPolicy>
  {
    try await self.updateAccessPolicy(withPolling: withPolling, options: .init())
  }

  public func updateAccessPolicy(
    withPolling: UpdateAccessPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<AccessPolicy> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<AccessPolicy>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteAccessPolicy(request: DeleteAccessPolicyRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteAccessPolicy(request: request, options: .init())
  }

  public func deleteAccessPolicy(
    request: DeleteAccessPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteAccessPolicy(withPolling: DeleteAccessPolicyRequest) async throws
    -> any GoogleCloudGax.PollableOperation<Swift.Void>
  {
    try await self.deleteAccessPolicy(withPolling: withPolling, options: .init())
  }

  public func deleteAccessPolicy(
    withPolling: DeleteAccessPolicyRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteAccessPolicy(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let request = DeleteAccessPolicyRequest().with {
      $0.name = name
    }
    return try await self.deleteAccessPolicy(withPolling: request)
  }

  public func listAccessPolicies(request: ListAccessPoliciesRequest) async throws
    -> GoogleIAMV3.ListAccessPoliciesResponse
  {
    try await self.listAccessPolicies(request: request, options: .init())
  }

  public func listAccessPolicies(
    request: ListAccessPoliciesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIAMV3.ListAccessPoliciesResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listAccessPolicies(
    byItem: ListAccessPoliciesRequest
  ) throws -> any AsyncSequence<AccessPolicy, Swift.Error> {
    try self.listAccessPolicies(byItem: byItem, options: .init())
  }

  public func listAccessPolicies(
    byItem: ListAccessPoliciesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<AccessPolicy, Swift.Error> {
    let listRpc = { (token: Swift.String) async throws -> GoogleIAMV3.ListAccessPoliciesResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listAccessPolicies(
    parent: Swift.String,
  ) throws -> any AsyncSequence<AccessPolicy, Swift.Error> {
    let request = ListAccessPoliciesRequest().with {
      $0.parent = parent
    }
    return try self.listAccessPolicies(byItem: request)
  }

  public func searchAccessPolicyBindings(request: SearchAccessPolicyBindingsRequest) async throws
    -> GoogleIAMV3.SearchAccessPolicyBindingsResponse
  {
    try await self.searchAccessPolicyBindings(request: request, options: .init())
  }

  public func searchAccessPolicyBindings(
    request: SearchAccessPolicyBindingsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleIAMV3.SearchAccessPolicyBindingsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func searchAccessPolicyBindings(
    byItem: SearchAccessPolicyBindingsRequest
  ) throws -> any AsyncSequence<PolicyBinding, Swift.Error> {
    try self.searchAccessPolicyBindings(byItem: byItem, options: .init())
  }

  public func searchAccessPolicyBindings(
    byItem: SearchAccessPolicyBindingsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<PolicyBinding, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleIAMV3.SearchAccessPolicyBindingsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func searchAccessPolicyBindings(
    name: Swift.String,
  ) throws -> any AsyncSequence<PolicyBinding, Swift.Error> {
    let request = SearchAccessPolicyBindingsRequest().with {
      $0.name = name
    }
    return try self.searchAccessPolicyBindings(byItem: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }
}
