// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
import GoogleGax
import struct Logging.Logger

extension Clients {
  final class AccessPoliciesLogging: AccessPoliciesStub {
    let inner: any AccessPoliciesStub
    let logger: Logger

    public init(_ inner: any AccessPoliciesStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-iam-v3"
      logger[metadataKey: "gcp.client.service"] = "iam"
      logger[metadataKey: "gcp.experimental.swift.client"] = "AccessPolicies"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func createAccessPolicy(
      request: CreateAccessPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createAccessPolicy",
        action: {
          (r: CreateAccessPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createAccessPolicy(request: r, options: o)
        })
    }

    public func getAccessPolicy(
      request: GetAccessPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV3.AccessPolicy {
      try await self._intercept(
        request: request,
        options: options,
        name: "getAccessPolicy",
        action: {
          (r: GetAccessPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV3.AccessPolicy
          in
          return try await self.inner.getAccessPolicy(request: r, options: o)
        })
    }

    public func updateAccessPolicy(
      request: UpdateAccessPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateAccessPolicy",
        action: {
          (r: UpdateAccessPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateAccessPolicy(request: r, options: o)
        })
    }

    public func deleteAccessPolicy(
      request: DeleteAccessPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteAccessPolicy",
        action: {
          (r: DeleteAccessPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteAccessPolicy(request: r, options: o)
        })
    }

    public func listAccessPolicies(
      request: ListAccessPoliciesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV3.ListAccessPoliciesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listAccessPolicies",
        action: {
          (r: ListAccessPoliciesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV3.ListAccessPoliciesResponse
          in
          return try await self.inner.listAccessPolicies(request: r, options: o)
        })
    }

    public func searchAccessPolicyBindings(
      request: SearchAccessPolicyBindingsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV3.SearchAccessPolicyBindingsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "searchAccessPolicyBindings",
        action: {
          (r: SearchAccessPolicyBindingsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV3.SearchAccessPolicyBindingsResponse
          in
          return try await self.inner.searchAccessPolicyBindings(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }
  }
}
