// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// An IAM access policy resource.
public struct AccessPolicy: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Identifier. The resource name of the access policy.
  ///
  /// The following formats are supported:
  ///
  /// * `projects/{project_id}/locations/{location}/accessPolicies/{policy_id}`
  /// * `projects/{project_number}/locations/{location}/accessPolicies/{policy_id}`
  /// * `folders/{folder_id}/locations/{location}/accessPolicies/{policy_id}`
  /// * `organizations/{organization_id}/locations/{location}/accessPolicies/{policy_id}`
  public var name: Swift.String = Swift.String()

  /// Output only. The globally unique ID of the access policy.
  public var uid: Swift.String = Swift.String()

  /// Optional. The etag for the access policy.
  /// If this is provided on update, it must match the server's etag.
  public var etag: Swift.String = Swift.String()

  /// Optional. The description of the access policy. Must be less than
  /// or equal to 63 characters.
  public var displayName: Swift.String = Swift.String()

  /// Optional. User defined annotations. See
  /// https://google.aip.dev/148#annotations for more details such as format and
  /// size limitations
  public var annotations: [Swift.String: Swift.String] = [:]

  /// Output only. The time when the access policy was created.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The time when the access policy was most recently
  /// updated.
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// Optional. The details for the access policy.
  public var details: AccessPolicyDetails? = nil

  /// Initialize a new instance of `AccessPolicy`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = AccessPolicy().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.iam.v3.AccessPolicy"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
