// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Request message for CreatePrincipalAccessBoundaryPolicyRequest method.
public struct CreatePrincipalAccessBoundaryPolicyRequest: Codable, Equatable, GoogleWKT
    ._AnyPackable,
  Sendable
{
  /// Required. The parent resource where this principal access boundary policy
  /// will be created. Only organizations are supported.
  ///
  /// Format:
  ///   `organizations/{organization_id}/locations/{location}`
  public var parent: Swift.String = Swift.String()

  /// Required. The ID to use for the principal access boundary policy, which
  /// will become the final component of the principal access boundary policy's
  /// resource name.
  ///
  /// This value must start with a lowercase letter followed by up to 62
  /// lowercase letters, numbers, hyphens, or dots. Pattern,
  /// /[a-z][a-z0-9-\.]{2,62}/.
  public var principalAccessBoundaryPolicyId: Swift.String = Swift.String()

  /// Required. The principal access boundary policy to create.
  public var principalAccessBoundaryPolicy: PrincipalAccessBoundaryPolicy? = nil

  /// Optional. If set, validate the request and preview the creation, but do not
  /// actually post it.
  public var validateOnly: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `CreatePrincipalAccessBoundaryPolicyRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreatePrincipalAccessBoundaryPolicyRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let parent = CodingKeys(stringValue: "parent")
    static let principalAccessBoundaryPolicyId = CodingKeys(
      stringValue: "principalAccessBoundaryPolicyId")
    static let principalAccessBoundaryPolicy = CodingKeys(
      stringValue: "principalAccessBoundaryPolicy")
    static let validateOnly = CodingKeys(stringValue: "validateOnly")

    static let _knownKeys: Set<Swift.String> = [
      "parent",
      "principalAccessBoundaryPolicyId",
      "principalAccessBoundaryPolicy",
      "validateOnly",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .parent) {
      self.parent = value
    }
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .principalAccessBoundaryPolicyId)
    {
      self.principalAccessBoundaryPolicyId = value
    }
    self.principalAccessBoundaryPolicy = try container.decodeIfPresent(
      PrincipalAccessBoundaryPolicy.self, forKey: .principalAccessBoundaryPolicy)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .validateOnly) {
      self.validateOnly = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parent, forKey: .parent)
    try container.encode(
      self.principalAccessBoundaryPolicyId, forKey: .principalAccessBoundaryPolicyId)
    try container.encodeIfPresent(
      self.principalAccessBoundaryPolicy, forKey: .principalAccessBoundaryPolicy)
    try container.encode(self.validateOnly, forKey: .validateOnly)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.iam.v3.CreatePrincipalAccessBoundaryPolicyRequest"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
