// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Request message for CreateAccessPolicy method.
public struct CreateAccessPolicyRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The parent resource where this access policy will be created.
  ///
  /// Format:
  ///   `projects/{project_id}/locations/{location}`
  ///   `projects/{project_number}/locations/{location}`
  ///   `folders/{folder_id}/locations/{location}`
  ///   `organizations/{organization_id}/locations/{location}`
  public var parent: Swift.String = Swift.String()

  /// Required. The ID to use for the access policy, which
  /// will become the final component of the access policy's
  /// resource name.
  ///
  /// This value must start with a lowercase letter followed by up to 62
  /// lowercase letters, numbers, hyphens, or dots. Pattern,
  /// /[a-z][a-z0-9-\.]{2,62}/.
  ///
  /// This value must be unique among all access policies with the same parent.
  public var accessPolicyId: Swift.String = Swift.String()

  /// Required. The access policy to create.
  public var accessPolicy: AccessPolicy? = nil

  /// Optional. If set, validate the request and preview the creation, but do not
  /// actually post it.
  public var validateOnly: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `CreateAccessPolicyRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = CreateAccessPolicyRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.iam.v3.CreateAccessPolicyRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
