// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Request message for ListAccessPolicies method.
public struct ListAccessPoliciesRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The parent resource, which owns the collection of access policy
  /// resources.
  ///
  /// Format:
  ///   `projects/{project_id}/locations/{location}`
  ///   `projects/{project_number}/locations/{location}`
  ///   `folders/{folder_id}/locations/{location}`
  ///   `organizations/{organization_id}/locations/{location}`
  public var parent: Swift.String = Swift.String()

  /// Optional. The maximum number of access policies to return. The
  /// service may return fewer than this value.
  ///
  /// If unspecified, at most 50 access policies will be returned. Valid value
  /// ranges from 1 to 1000; values above 1000 will be coerced to 1000.
  public var pageSize: Swift.Int32 = Swift.Int32()

  /// Optional. A page token, received from a previous
  /// `ListAccessPolicies` call. Provide this to retrieve the
  /// subsequent page.
  ///
  /// When paginating, all other parameters provided to
  /// `ListAccessPolicies` must match the call that provided the
  /// page token.
  public var pageToken: Swift.String = Swift.String()

  /// Initialize a new instance of `ListAccessPoliciesRequest`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ListAccessPoliciesRequest().with { $0.parent = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.iam.v3.ListAccessPoliciesRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
