// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
@_spi(GoogleCloudInternal) public import GoogleLongRunning
@_spi(GoogleCloudInternal) public import GoogleWKT
@_spi(GoogleCloudInternal) public import GoogleGax

/// An interface for managing Identity and Access Management (IAM) policy
/// bindings.
///
/// @Snippet(path: "PolicyBindingsQuickstart")
public final class PolicyBindingsClient: Clients.PolicyBindingsProtocol, Sendable {
  let inner: any Clients.PolicyBindingsStub
  let pollingErrorPolicy: GoogleGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleGax.BackoffPolicy

  /// Creates a new `PolicyBindingsClient` instance.
  public init(_ options: GoogleGax.ClientOptions = .init()) throws {
    var inner: any Clients.PolicyBindingsStub = try Clients.PolicyBindingsTransport(options)
    inner = Clients.PolicyBindingsRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.PolicyBindingsLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Creates a policy binding and returns a long-running operation.
  /// Callers will need the IAM permissions on both the policy and target.
  /// After the binding is created, the policy is applied to the target.
  ///
  /// @Snippet(path: "PolicyBindings_CreatePolicyBinding")
  public func createPolicyBinding(
    request: CreatePolicyBindingRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createPolicyBinding(request: request, options: options)
  }

  /// Creates a policy binding and returns a long-running operation.
  /// Callers will need the IAM permissions on both the policy and target.
  /// After the binding is created, the policy is applied to the target.
  ///
  /// @Snippet(path: "PolicyBindings_CreatePolicyBinding")
  public func createPolicyBindingPollingUntilDone(
    request: CreatePolicyBindingRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<PolicyBinding> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<PolicyBinding>.State in
      return try op._extractStatus(PolicyBinding.self)
    }
    let rawOp = try await self.createPolicyBinding(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<PolicyBinding>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Gets a policy binding.
  ///
  /// @Snippet(path: "PolicyBindings_GetPolicyBinding")
  public func getPolicyBinding(
    request: GetPolicyBindingRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV3.PolicyBinding {
    try await self.inner.getPolicyBinding(request: request, options: options)
  }

  /// Updates a policy binding and returns a long-running operation.
  /// Callers will need the IAM permissions on the policy and target in the
  /// binding to update. Target and policy are immutable and cannot be updated.
  ///
  /// @Snippet(path: "PolicyBindings_UpdatePolicyBinding")
  public func updatePolicyBinding(
    request: UpdatePolicyBindingRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updatePolicyBinding(request: request, options: options)
  }

  /// Updates a policy binding and returns a long-running operation.
  /// Callers will need the IAM permissions on the policy and target in the
  /// binding to update. Target and policy are immutable and cannot be updated.
  ///
  /// @Snippet(path: "PolicyBindings_UpdatePolicyBinding")
  public func updatePolicyBindingPollingUntilDone(
    request: UpdatePolicyBindingRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<PolicyBinding> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<PolicyBinding>.State in
      return try op._extractStatus(PolicyBinding.self)
    }
    let rawOp = try await self.updatePolicyBinding(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<PolicyBinding>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Deletes a policy binding and returns a long-running operation.
  /// Callers will need the IAM permissions on both the policy and target.
  /// After the binding is deleted, the policy no longer applies to the target.
  ///
  /// @Snippet(path: "PolicyBindings_DeletePolicyBinding")
  public func deletePolicyBinding(
    request: DeletePolicyBindingRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deletePolicyBinding(request: request, options: options)
  }

  /// Deletes a policy binding and returns a long-running operation.
  /// Callers will need the IAM permissions on both the policy and target.
  /// After the binding is deleted, the policy no longer applies to the target.
  ///
  /// @Snippet(path: "PolicyBindings_DeletePolicyBinding")
  public func deletePolicyBindingPollingUntilDone(
    request: DeletePolicyBindingRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      @Sendable (op: GoogleLongRunning.Operation) throws
        -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deletePolicyBinding(request: request, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists policy bindings.
  ///
  /// @Snippet(path: "PolicyBindings_ListPolicyBindings")
  public func listPolicyBindings(
    request: ListPolicyBindingsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV3.ListPolicyBindingsResponse {
    try await self.inner.listPolicyBindings(request: request, options: options)
  }

  /// Search policy bindings by target. Returns all policy binding objects bound
  /// directly to target.
  ///
  /// @Snippet(path: "PolicyBindings_SearchTargetPolicyBindings")
  public func searchTargetPolicyBindings(
    request: SearchTargetPolicyBindingsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV3.SearchTargetPolicyBindingsResponse {
    try await self.inner.searchTargetPolicyBindings(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "PolicyBindings_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `PolicyBindingsClient`.
  ///
  /// To mock `PolicyBindingsClient` change your functions to receive
  /// `some PolicyBindingsProtocol` or `any PolicyBindingsProtocol`
  /// and pass a mock implementation in your tests.
  public protocol PolicyBindingsProtocol: Sendable {
    /// See `PolicyBindingsClient.createPolicyBinding`.
    func createPolicyBinding(
      request: CreatePolicyBindingRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `PolicyBindingsClient.createPolicyBinding`.
    func createPolicyBindingPollingUntilDone(
      request: CreatePolicyBindingRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<PolicyBinding>

    /// See `PolicyBindingsClient.getPolicyBinding`.
    func getPolicyBinding(
      request: GetPolicyBindingRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV3.PolicyBinding

    /// See `PolicyBindingsClient.updatePolicyBinding`.
    func updatePolicyBinding(
      request: UpdatePolicyBindingRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `PolicyBindingsClient.updatePolicyBinding`.
    func updatePolicyBindingPollingUntilDone(
      request: UpdatePolicyBindingRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<PolicyBinding>

    /// See `PolicyBindingsClient.deletePolicyBinding`.
    func deletePolicyBinding(
      request: DeletePolicyBindingRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `PolicyBindingsClient.deletePolicyBinding`.
    func deletePolicyBindingPollingUntilDone(
      request: DeletePolicyBindingRequest, options: GoogleGax.RequestOptions
    ) async throws -> any GoogleGax.PollableOperation<Swift.Void>

    /// See `PolicyBindingsClient.listPolicyBindings`.
    func listPolicyBindings(
      request: ListPolicyBindingsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV3.ListPolicyBindingsResponse

    /// See `PolicyBindingsClient.searchTargetPolicyBindings`.
    func searchTargetPolicyBindings(
      request: SearchTargetPolicyBindingsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV3.SearchTargetPolicyBindingsResponse
  }
}

// Default implementations
extension Clients.PolicyBindingsProtocol {
  public func createPolicyBinding(request: CreatePolicyBindingRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createPolicyBinding(request: request, options: .init())
  }

  public func createPolicyBinding(
    request: CreatePolicyBindingRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func createPolicyBindingPollingUntilDone(request: CreatePolicyBindingRequest) async throws
    -> any GoogleGax.PollableOperation<PolicyBinding>
  {
    try await self.createPolicyBindingPollingUntilDone(request: request, options: .init())
  }

  public func createPolicyBindingPollingUntilDone(
    request: CreatePolicyBindingRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<PolicyBinding> {
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<PolicyBinding>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createPolicyBindingPollingUntilDone(
    parent: Swift.String,
    policyBinding: PolicyBinding?,
    policyBindingId: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<PolicyBinding> {
    let request = CreatePolicyBindingRequest().with {
      $0.parent = parent
      $0.policyBinding = policyBinding
      $0.policyBindingId = policyBindingId
    }
    return try await self.createPolicyBindingPollingUntilDone(request: request)
  }

  public func getPolicyBinding(request: GetPolicyBindingRequest) async throws
    -> GoogleIAMV3.PolicyBinding
  {
    try await self.getPolicyBinding(request: request, options: .init())
  }

  public func getPolicyBinding(
    request: GetPolicyBindingRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV3.PolicyBinding {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getPolicyBinding(
    name: Swift.String,
  ) async throws -> GoogleIAMV3.PolicyBinding {
    let request = GetPolicyBindingRequest().with {
      $0.name = name
    }
    return try await self.getPolicyBinding(request: request)
  }

  public func updatePolicyBinding(request: UpdatePolicyBindingRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updatePolicyBinding(request: request, options: .init())
  }

  public func updatePolicyBinding(
    request: UpdatePolicyBindingRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func updatePolicyBindingPollingUntilDone(request: UpdatePolicyBindingRequest) async throws
    -> any GoogleGax.PollableOperation<PolicyBinding>
  {
    try await self.updatePolicyBindingPollingUntilDone(request: request, options: .init())
  }

  public func updatePolicyBindingPollingUntilDone(
    request: UpdatePolicyBindingRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<PolicyBinding> {
    let poll = {
      @Sendable () async throws -> GoogleGax._PollableOperationImpl<PolicyBinding>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updatePolicyBindingPollingUntilDone(
    policyBinding: PolicyBinding?,
    updateMask: GoogleWKT.WKTFieldMask?,
  ) async throws -> any GoogleGax.PollableOperation<PolicyBinding> {
    let request = UpdatePolicyBindingRequest().with {
      $0.policyBinding = policyBinding
      $0.updateMask = updateMask
    }
    return try await self.updatePolicyBindingPollingUntilDone(request: request)
  }

  public func deletePolicyBinding(request: DeletePolicyBindingRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deletePolicyBinding(request: request, options: .init())
  }

  public func deletePolicyBinding(
    request: DeletePolicyBindingRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func deletePolicyBindingPollingUntilDone(request: DeletePolicyBindingRequest) async throws
    -> any GoogleGax.PollableOperation<Swift.Void>
  {
    try await self.deletePolicyBindingPollingUntilDone(request: request, options: .init())
  }

  public func deletePolicyBindingPollingUntilDone(
    request: DeletePolicyBindingRequest, options: GoogleGax.RequestOptions
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let poll = { @Sendable () async throws -> GoogleGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleGax.RequestError.unimplemented
    }
    return GoogleGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deletePolicyBindingPollingUntilDone(
    name: Swift.String,
  ) async throws -> any GoogleGax.PollableOperation<Swift.Void> {
    let request = DeletePolicyBindingRequest().with {
      $0.name = name
    }
    return try await self.deletePolicyBindingPollingUntilDone(request: request)
  }

  public func listPolicyBindings(request: ListPolicyBindingsRequest) async throws
    -> GoogleIAMV3.ListPolicyBindingsResponse
  {
    try await self.listPolicyBindings(request: request, options: .init())
  }

  public func listPolicyBindings(
    request: ListPolicyBindingsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV3.ListPolicyBindingsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func listPolicyBindingsByItems(
    request: ListPolicyBindingsRequest
  ) -> any AsyncSequence<PolicyBinding, Swift.Error> & Sendable {
    self.listPolicyBindingsByItems(request: request, options: .init())
  }

  /// Lists policy bindings.
  ///
  /// @Snippet(path: "PolicyBindings_ListPolicyBindings")
  public func listPolicyBindingsByItems(
    request: ListPolicyBindingsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<PolicyBinding, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleIAMV3.ListPolicyBindingsResponse in
      var request = request
      request.pageToken = token
      return try await self.listPolicyBindings(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listPolicyBindingsByItems(
    parent: Swift.String,
  ) -> any AsyncSequence<PolicyBinding, Swift.Error> & Sendable {
    let request = ListPolicyBindingsRequest().with {
      $0.parent = parent
    }
    return self.listPolicyBindingsByItems(request: request)
  }

  public func searchTargetPolicyBindings(request: SearchTargetPolicyBindingsRequest) async throws
    -> GoogleIAMV3.SearchTargetPolicyBindingsResponse
  {
    try await self.searchTargetPolicyBindings(request: request, options: .init())
  }

  public func searchTargetPolicyBindings(
    request: SearchTargetPolicyBindingsRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleIAMV3.SearchTargetPolicyBindingsResponse {
    throw GoogleGax.RequestError.unimplemented
  }

  public func searchTargetPolicyBindingsByItems(
    request: SearchTargetPolicyBindingsRequest
  ) -> any AsyncSequence<PolicyBinding, Swift.Error> & Sendable {
    self.searchTargetPolicyBindingsByItems(request: request, options: .init())
  }

  /// Search policy bindings by target. Returns all policy binding objects bound
  /// directly to target.
  ///
  /// @Snippet(path: "PolicyBindings_SearchTargetPolicyBindings")
  public func searchTargetPolicyBindingsByItems(
    request: SearchTargetPolicyBindingsRequest, options: GoogleGax.RequestOptions
  ) -> any AsyncSequence<PolicyBinding, Swift.Error> & Sendable {
    let listRpc = {
      @Sendable (token: Swift.String) async throws -> GoogleIAMV3.SearchTargetPolicyBindingsResponse
      in
      var request = request
      request.pageToken = token
      return try await self.searchTargetPolicyBindings(request: request, options: options)
    }
    return GoogleGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func searchTargetPolicyBindingsByItems(
    parent: Swift.String,
    target: Swift.String,
  ) -> any AsyncSequence<PolicyBinding, Swift.Error> & Sendable {
    let request = SearchTargetPolicyBindingsRequest().with {
      $0.parent = parent
      $0.target = target
    }
    return self.searchTargetPolicyBindingsByItems(request: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }
}
