// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

extension Clients {
  protocol PolicyBindingsStub: Sendable {
    func createPolicyBinding(
      request: CreatePolicyBindingRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getPolicyBinding(
      request: GetPolicyBindingRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV3.PolicyBinding

    func updatePolicyBinding(
      request: UpdatePolicyBindingRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deletePolicyBinding(
      request: DeletePolicyBindingRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listPolicyBindings(
      request: ListPolicyBindingsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV3.ListPolicyBindingsResponse

    func searchTargetPolicyBindings(
      request: SearchTargetPolicyBindingsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleIAMV3.SearchTargetPolicyBindingsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation
  }
}
