// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
@_spi(GoogleCloudInternal) import GoogleGax

extension Clients {
  final class PrincipalAccessBoundaryPoliciesRetry: PrincipalAccessBoundaryPoliciesStub {
    let inner: any PrincipalAccessBoundaryPoliciesStub
    let options: GoogleGax.ClientOptions

    public init(_ inner: any PrincipalAccessBoundaryPoliciesStub, options: GoogleGax.ClientOptions)
    {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func createPrincipalAccessBoundaryPolicy(
      request: CreatePrincipalAccessBoundaryPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreatePrincipalAccessBoundaryPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createPrincipalAccessBoundaryPolicy(request: r, options: o)
        })
    }

    public func getPrincipalAccessBoundaryPolicy(
      request: GetPrincipalAccessBoundaryPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV3.PrincipalAccessBoundaryPolicy {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetPrincipalAccessBoundaryPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV3.PrincipalAccessBoundaryPolicy
          in
          return try await self.inner.getPrincipalAccessBoundaryPolicy(request: r, options: o)
        })
    }

    public func updatePrincipalAccessBoundaryPolicy(
      request: UpdatePrincipalAccessBoundaryPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdatePrincipalAccessBoundaryPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updatePrincipalAccessBoundaryPolicy(request: r, options: o)
        })
    }

    public func deletePrincipalAccessBoundaryPolicy(
      request: DeletePrincipalAccessBoundaryPolicyRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeletePrincipalAccessBoundaryPolicyRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deletePrincipalAccessBoundaryPolicy(request: r, options: o)
        })
    }

    public func listPrincipalAccessBoundaryPolicies(
      request: ListPrincipalAccessBoundaryPoliciesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV3.ListPrincipalAccessBoundaryPoliciesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListPrincipalAccessBoundaryPoliciesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleIAMV3.ListPrincipalAccessBoundaryPoliciesResponse
          in
          return try await self.inner.listPrincipalAccessBoundaryPolicies(request: r, options: o)
        })
    }

    public func searchPrincipalAccessBoundaryPolicyBindings(
      request: SearchPrincipalAccessBoundaryPolicyBindingsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleIAMV3.SearchPrincipalAccessBoundaryPolicyBindingsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: SearchPrincipalAccessBoundaryPolicyBindingsRequest, o: GoogleGax.RequestOptions)
            async throws -> GoogleIAMV3.SearchPrincipalAccessBoundaryPolicyBindingsResponse
          in
          return try await self.inner.searchPrincipalAccessBoundaryPolicyBindings(
            request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }
  }
}
